[package]
name = "plio-testbench"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
plio-logical-model = { path = "../../plio-logical/rust" }
qli-model = { path = "../../qli/rust" }
pti-model = { path = "../../pti/rust" }
plio-tx-model = { path = "../../plio-tx/rust" }
plio-qic-model = { path = "../../qic/rust" }
