[workspace]
resolver = "2"
members = [
    "plio-logical/rust",
    "qli/rust",
    "qli16/rust",
    "pti/rust",
    "plio-tx/rust",
    "qic/rust",
    "testbench/rust",
    "naked-card/rust",
    "qdx-a/rust",
    "qdx-a-card/rust",
    "trace/rust",
    "plio-rax-host/rust",
    "plio-rax-host/m2-rust",
]

[workspace.package]
edition = "2021"
license = "MIT"
